version: '3'
services:
  env:
    image: "python:3.6-slim"
    links:
      - dynamodb
    environment:
      - DEBUG=1
      - DYNAMODB_ENDPOINT_URL=http://dynamodb:8000
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=ap-northeast-1
    working_dir: /opt/hikidashi
    volumes:
      - .:/opt/hikidashi
    command: /bin/bash -c "pip install -r requirements.txt && pip install -e .[test] && hikidashi runserver"
  dynamodb:
    image: "tray/dynamodb-local"
    command: -dbPath /var/lib/dynamodb -sharedDb -port 8000
    volumes:
      - dynamodb-volume:/var/lib/dynamodb
volumes:
  dynamodb-volume: